# This file was autogenerated in base/version_git.sh
struct GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "0d7248e2ff65bd6886ba3f003bf5aeab929edab5",
    "0d7248e*",
    "(detached from v0.6.1)",
    0,
    "2017-10-24 22:15 UTC",
    true,
    0,
    1508883336.
)
